repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
      - id: clang-tidy
        args: [--export-fixes=-]
        additional_dependencies: [clang-tidy]
        exclude: test_.*
        files: \.(cpp|cxx|cc|c|hpp|hxx|hh|h)$
        args: [
          -p=build,
        ]
