#!/usr/bin/env bash

report_error() {
    local SCRIPT_NAME=$(basename "$0")
    local ERROR_MSG="$1"
    local EXIT_CODE="${2:-1}"  # Default exit code: 1 if not provided

    echo -e "ERROR ${SCRIPT_NAME}:\033[0m $ERROR_MSG" >&2

    exit "$EXIT_CODE"
}

if [[ ! -f "CMakeCache.txt" ]]; then
    report_error "Not in directory with cmake build output."
fi

lcov --capture --directory . --output-file coverage.info
lcov --remove coverage.info '/usr/include/*' '*/test_*' 'catch2/*' -o filtered.info

COVERAGE_PERCENT=$(lcov --summary filtered.info 2>&1 | \
    grep -P -o 'lines\.*: \d+\.\d%' | \
    awk '{print $2}' | \
    sed 's/%//')

if (( $(echo "$COVERAGE_PERCENT < 100" | bc -l) )); then
    report_error "Coverage is not 100% (it's ${COVERAGE_PERCENT}%)"
fi
